/* $OpenBSD$ */

/*
 * Copyright (c) 2016 joshua stein <jcs@openbsd.org>
 *
 * Permission to use, copy, modify, and distribute this software for any
 * purpose with or without fee is hereby granted, provided that the above
 * copyright notice and this permission notice appear in all copies.
 *
 * THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
 * WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
 * ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
 * WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
 * ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
 * OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
 */

#define COLOR_DEFAULT_BG	0
#define COLOR_DEFAULT_FG	7

#define COLOR_BLACK		0x00
#define COLOR_BLUE		0x01
#define COLOR_GREEN		0x02
#define COLOR_CYAN		(COLOR_BLUE | COLOR_GREEN)
#define COLOR_RED		0x04
#define COLOR_MAGENTA		(COLOR_BLUE | COLOR_RED)
#define COLOR_BROWN		(COLOR_GREEN | COLOR_RED)
#define COLOR_LIGHTGRAY		(COLOR_BLUE | COLOR_GREEN | COLOR_RED)
#define COLOR_BRIGHT		0x08
#define COLOR_BRIGHT_BLACK	(COLOR_BRIGHT)
#define COLOR_BRIGHT_BLUE	(COLOR_BLUE | COLOR_BRIGHT)
#define COLOR_BRIGHT_GREEN	(COLOR_GREEN | COLOR_BRIGHT)
#define COLOR_BRIGHT_CYAN	(COLOR_CYAN | COLOR_BRIGHT)
#define COLOR_BRIGHT_RED	(COLOR_RED | COLOR_BRIGHT)
#define COLOR_BRIGHT_MAGENTA	(COLOR_MAGENTA | COLOR_BRIGHT)
#define COLOR_BRIGHT_YELLOW	(COLOR_BROWN | COLOR_BRIGHT)
#define COLOR_BRIGHT_WHITE	(COLOR_BLUE | COLOR_GREEN | COLOR_RED | COLOR_BRIGHT)
